feat(core/wordle): wordle
koishijs/wordle pull request #1
Opened 2023-02-07 04:53 UTC by Seidko

# preview
![image](https://user-images.githubusercontent.com/64234553/217151563-703e2140-34cf-4bb0-847f-e1404d6263fc.png)

2023-02-12 14:43 UTC, MaikoTan commented
I added a helper function in [koishijs/wordle@`f56cb45` (#1)](https://github.com/koishijs/wordle/pull/1/commits/f56cb45575539094e0174aa08bf9f78bfd2e0ea8) so then you could install `vscode-styled-components` extension to get a fully highlighted CSS.

2023-02-12 14:45 UTC, MaikoTan commented
Also fixed linting

2023-03-01 15:19 UTC, Seidko commented
<message forward>
<message>This is a XSS XD</message>
</message>

2023-03-02 03:07 UTC, MaikoTan requested changes
Looks good to me, several comments but it is okay to merge.

2023-03-02 03:07 UTC, MaikoTan commented on packages/wordle/src/index.ts
> +    imageMode: Schema.boolean().default(true),
`imageMode` should be the configuration of the core, je pense.

2023-03-02 03:07 UTC, MaikoTan commented on packages/wordle/src/locales/zh-CN.yml
> +      lose: 好可惜……再接再厉吧！
Just a lint complains, always append a new line at the end of file.

2023-03-02 03:07 UTC, MaikoTan commented on packages/core/src/locales/zh-CN.yml
> +      Wordle
```suggestion
      {name}
```

Others games are not called `Wordle`, non hard-coding ici.

2023-03-02 03:07 UTC, MaikoTan commented on packages/core/src/index.tsx
> +    const textMode = !(this.config.imageMode && this.ctx.puppeteer)
Better to print a warning message says something like `WARN: No puppeteer installed, switch to text mode.`

2023-03-02 06:04 UTC, Seidko commented on packages/wordle/src/index.ts
> +import { WordleCore } from '@koishijs/wordle/src'
but if I didn't add `src`, ts will start complain `cannot found module`.

2023-03-02 06:23 UTC, MaikoTan commented on packages/wordle/src/index.ts
> +import { WordleCore } from '@koishijs/wordle/src'
Mught there be something wrong about the tsconfig or IDEs, I would take a look later. But importing from `src` is incorrect way, please don't.

2023-07-01 14:17 UTC, closed without merging